namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
subChartsRevision: HEAD
repoURL: https://github.com/nearform/initium-platform.git
apps:
  # ArgoCD - https://github.com/argoproj/argo-cd/
  argocd:
    name: argocd
    path: addons/argocd/
    targetNamespace: argocd
    excluded: true

  # Cert-manager - https://cert-manager.io/
  cert-manager:
    name: cert-manager
    path: addons/cert-manager/
    targetNamespace: cert-manager
    excluded: false

  # Dex - https://dexidp.io/
  dex:
    name: dex
    path: addons/dex/
    targetNamespace: dex

  # Prometheus + Operator - https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  # External grafana app needs to be deployed together with this stack
  kube-prometheus-stack:
    name: kube-prometheus-stack
    path: addons/kube-prometheus-stack/
    targetNamespace: prometheus
    serverSideApply: true

  # Istio - https://istio.io/
  istio-base:
    name: istio-base
    path: addons/istio/base/
    targetNamespace: istio-system
    syncWave: -20

  istiod:
    name: istiod
    path: addons/istio/istiod/
    targetNamespace: istio-system
    syncWave: -20

  istio-ingressgateway:
    name: istio-ingressgateway
    path: addons/istio/ingressgateway/
    targetNamespace: istio-ingress

  # Knative - https://knative.dev/
  knative:
    name: knative
    path: addons/knative/
    targetNamespace: knative

  # OpenTelemetry - https://opentelemetry.io/
  opentelemetry-collector:
    name: opentelemetry-collector
    path: addons/opentelemetry-collector/
    targetNamespace: opentelemetry

  # Grafana Loki - https://grafana.com/oss/loki/
  loki:
    name: loki
    path: addons/loki/
    targetNamespace: loki
    ignoreDifferences:
      - group: apps
        kind: StatefulSet
        jsonPointers:
          - /spec/persistentVolumeClaimRetentionPolicy

  # Grafana - https://grafana.com/oss/
  grafana:
    name: grafana
    path: addons/grafana/
    targetNamespace: grafana

  # Kubernetes Replicator
  kubernetes-replicator:
    image:
      repository: quay.io/mittwald/kubernetes-replicator
      #tag: stable # if no tag is given, the chart's appVersion is used
      pullPolicy: Always
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    grantClusterAdmin: false
    automountServiceAccountToken: true
    args: []
      # - -resync-period=30m
      # - -allow-all=false

    ## Deployment strategy / DaemonSet updateStrategy
    ##
    updateStrategy: {}
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxUnavailable: 1

    serviceAccount:
      create: false
      annotations: {}
      name:
      privileges: []
      automountServiceAccountToken: true
      # - apiGroups: [""]
      #   resources: ["configmaps"]
    podSecurityContext: {}
      # fsGroup: 2000

    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    priorityClassName: ""

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}

    podLabels: {}

    podAnnotations: {}

    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
