namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
subChartsRevision: HEAD
repoURL: https://github.com/nearform/k8s-kurated-addons.git
apps:
  # ArgoCD - https://github.com/argoproj/argo-cd/
  argocd:
    name: argocd
    path: addons/argocd/
    targetNamespace: argocd
    excluded: true

  # Cert-manager - https://cert-manager.io/
  cert-manager:
    name: cert-manager
    path: addons/cert-manager/
    targetNamespace: cert-manager
    excluded: false

  # Dex - https://dexidp.io/
  dex:
    name: dex
    path: addons/dex/
    targetNamespace: dex

  # Prometheus + Operator - https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  # External grafana app needs to be deployed together with this stack
  kube-prometheus-stack:
    name: kube-prometheus-stack
    path: addons/kube-prometheus-stack/
    targetNamespace: prometheus
    serverSideApply: true

  # Istio - https://istio.io/
  istio-base:
    name: istio-base
    path: addons/istio/base/
    targetNamespace: istio-system
    syncWave: -20

  istiod:
    name: istiod
    path: addons/istio/istiod/
    targetNamespace: istio-system
    syncWave: -20

  istio-ingressgateway:
    name: istio-ingressgateway
    path: addons/istio/ingressgateway/
    targetNamespace: istio-ingress

  # Knative - https://knative.dev/
  knative:
    name: knative
    path: addons/knative/
    targetNamespace: knative

  # OpenTelemetry - https://opentelemetry.io/
  opentelemetry-collector:
    name: opentelemetry-collector
    path: addons/opentelemetry-collector/
    targetNamespace: opentelemetry

  # Grafana Loki - https://grafana.com/oss/loki/
  loki:
    name: loki
    path: addons/loki/
    targetNamespace: loki
    ignoreDifferences:
      - group: apps
        kind: StatefulSet
        jsonPointers:
          - /spec/persistentVolumeClaimRetentionPolicy

  # Grafana - https://grafana.com/oss/
  grafana:
    name: grafana
    path: addons/grafana/
    targetNamespace: grafana
