global:
  repoURL: https://github.com/nearform/k8s-kurated-addons.git
  projectName: default
  server: https://kubernetes.default.svc

defaults:
  targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

applications:
  # Cert-manager - https://cert-manager.io/
  - name: cert-manager
    enabled: false
    namespace: cert-manager
    path: addons/cert-manager
    valueFiles:
      - values.yaml

  # Dex - https://dexidp.io/
  - name: dex
    enabled: true
    namespace: dex
    path: addons/dex
    valueFiles:
      - values.yaml

  # Prometheus + Grafana + Operator - https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  - name: kube-prometheus-stack
    enabled: true
    namespace: prometheus
    path: addons/kube-prometheus-stack
    valueFiles:
      - values.yaml

  # Istio - https://istio.io/
  - name: istio-base
    enabled: true
    namespace: istio-system
    path: addons/istio/base
    valueFiles:
      - values.yaml
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "-1"

  - name: istiod
    enabled: true
    namespace: istio-system
    path: addons/istio/istiod
    valueFiles:
      - values.yaml
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "-1"

  - name: istio-ingressgateway
    enabled: true
    namespace: istio-system
    path: addons/istio/ingressgateway
    valueFiles:
      - values.yaml
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "-1"

  # Knative - https://knative.dev/
  - name: knative-operator
    enabled: true
    namespace: knative-operator
    path: addons/knative/operator
    valueFiles:
      - values.yaml

  - name: knative-serving
    enabled: true
    namespace: knative-serving
    path: addons/knative/serving
    valueFiles:
      - values.yaml

  - name: knative-eventing
    enabled: true
    namespace: knative-eventing
    path: addons/knative/eventing
    valueFiles:
      - values.yaml
