namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
subChartsRevision: HEAD
repoURL: https://github.com/nearform/initium-platform.git
apps:

  # Kubernetes Replicator
  kubernetes-replicator-source:
    name: kubernetes-replicator
    path: addons/kubernetes-replicator/
    targetNamespace: kubernetes-replicator
