apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kube-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.{{ .Values.externalDomain }}"
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - {{ .Values.gateway.host | quote }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.gateway.tlsCertName }}
      mode: SIMPLE
