apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dex
  namespace: dex
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.host }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.tlsCertName }}
      mode: SIMPLE
