apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: dex
spec:
  gateways:
  - dex
  hosts:
  - {{ .Values.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.dexServiceName }}
        port:
          number: {{ .Values.port }}
