repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
    - id: helmlint
  - repo: local
    hooks:
    -   id: tiltfile-validate
        name: Validate Tiltfile
        entry: ./scripts/tilt-validate.sh
        language: script
        files: ^Tiltfile$
