apiVersion: v1
kind: Secret
metadata:
  name: grafana-initial-admin-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  admin-user: {{ b64enc "admin" }}
  admin-password: {{ randAlphaNum 20 | b64enc }}
