{{- $name := .Values.externalDomain | required ".Values.externalDomain is required." -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  gateways:
  - {{ .Values.virtualService.gateway }}
  hosts:
  - {{ .Values.virtualService.internalHost  | quote }}
  - {{ .Values.virtualService.name}}.{{ .Values.externalDomain }}
  http:
  - route:
    - destination:
        host: {{ .Values.virtualService.serviceName }}
        port:
          number: {{ .Values.virtualService.port }}
