apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-podinfo-app
#  namespace: xxx TODO should this live in its own namespace?
spec:
  template:
    metadata:
      annotations:
        # For testing purposes set request-per-second to 1 to force scaling
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/metric: "rps"
      labels:
        service: "podinfo"
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:6.3.5
          ports:
            - containerPort: 9898
          imagePullPolicy: IfNotPresent
#          ports:
#            - name: http
#              containerPort: 9898
#              protocol: TCP
#            - name: http-metrics
#              containerPort: 9797
#              protocol: TCP
#            - name: grpc
#              containerPort: 9999
#              protocol: TCP
          command:
            - ./podinfo
            - --port=9898
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=info
            - --random-delay=false
            - --random-error=false
          env:
            - name: PODINFO_UI_COLOR
              value: "#34577c"
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
