apiVersion: v2
name: vault
description: vault chart
type: application
version: v0.0.1
dependencies:
  - name: vault
    alias: vault-source
    version: 1.12.1
    repository: https://helm.releases.hashicorp.com
