apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: dex
spec:
  gateways:
  - {{ .Values.istioConfig.gateway }}
  hosts:
  - {{ .Values.istioConfig.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.istioConfig.dexServiceName }}
        port:
          number: {{ .Values.istioConfig.port }}
