apiVersion: v2
name: metallb
description: metallb wrapper chart
type: application
version: v0.4.0 # x-release-please-version
dependencies:
  - name: metallb
    alias: metallb-source
    version: 0.14.8
    repository: https://metallb.github.io/metallb
