dex-source:
  config:
    issuer: https://dex.kube.local:32000

    storage:
      type: kubernetes
      config:
        inCluster: true

    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.kube.local:32000/callback

    staticClients:
    - id: kubelogin
      redirectURIs:
        - 'http://localhost:8000'
      name: 'Example App'
      secretEnv: KUBELOGIN_CLIENT_SECRET

  envVars:
  - name: GITHUB_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: github-client
        key: client-id
  - name: GITHUB_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: github-client
        key: client-secret

  - name: KUBELOGIN_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: kubelogin-client
        key: client-secret

istioConfig:
  gateway: istio-ingress/kube-gateway
  host: dex.kube.local
  port: 5556
  dexServiceName: dex-dex-source
