dex-source:
  config:
    # The base path of dex and the external name of the OpenID Connect service.
    # This is the canonical URL that all clients MUST use to refer to dex. If a
    # path is provided, dex's HTTP service will listen at a non-root URL.
    issuer: https://dex.kube.local:32000

    # See https://dexidp.io/docs/storage/ for more options
    storage:
      type: kubernetes
      config:
        inCluster: true

    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.kube.local:32000/callback

    staticClients:
    - id: example-app
      redirectURIs:
        - 'http://127.0.0.1:5555/callback'
      name: 'Example App'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  ingress:
    enabled: false

  envVars:
  - name: GITHUB_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: github-client
        key: client-id
  - name: GITHUB_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: github-client
        key: client-secret

  - name: EXAMPLE_APP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: example-app-client
        key: client-secret

istioConfig:
  gateway: istio-ingress/kube-gateway
  host: dex.kube.local
  port: 5556
  dexServiceName: dex-dex-source
