apiVersion: v2
name: opentelemetry-operator
description: OpenTelemetry Operator Helm chart for Kubernetes
type: application
version: v0.0.1 # x-release-please-version
dependencies:
  - name: opentelemetry-operator
    alias: otlp-operator-source
    version: 0.21.4
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: otlp-operator-source.enabled
