apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-kurated-addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: app-of-apps
    repoURL: ${KKA_REPO_URI}
    targetRevision: ${KKA_REPO_BRANCH}
    helm:
      values: |
        repoURL: ${KKA_REPO_URI}
        subChartsRevision: ${KKA_REPO_BRANCH}
        apps:
          dex:
            excluded: ${KKA_AOA_EXCLUDE_DEX}
          istio-base:
            excluded: ${KKA_AOA_EXCLUDE_ISTIO}
          istiod:
            excluded: ${KKA_AOA_EXCLUDE_ISTIO}
          istio-ingressgateway:
            excluded: ${KKA_AOA_EXCLUDE_ISTIO}
          knative-operator:
            excluded: ${KKA_AOA_EXCLUDE_KNATIVE}
          knative-serving:
            excluded: ${KKA_AOA_EXCLUDE_KNATIVE}
          knative-eventing:
            excluded: ${KKA_AOA_EXCLUDE_KNATIVE}
          kube-prometheus-stack:
            excluded: ${KKA_AOA_EXCLUDE_PROMETHEUSSTACK}
          opentelemetry-collector:
            excluded: ${KKA_AOA_EXCLUDE_OPENTELEMETRY_COLLECTOR}
          opentelemetry-operator:
            excluded: ${KKA_AOA_EXCLUDE_OPENTELEMETRY_OPERATOR}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
