apiVersion: v1
kind: Secret
metadata:
  name: initium-platform
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nearform/initium-platform.git
  # githubAppPrivateKey: ${GITHUB_APP_PRIVATE_KEY}
  # githubAppId: ${GITHUB_APP_ID}
  # githubAppInstallationId: ${GITHUB_APP_INSTALLATION_ID}
  # Use username and password if you don't have a GitHub App
  username: "${GH_USERNAME}"
  password: "${GH_PAT}"
