apiVersion: v2
name: Grafana
description: Grafana Helm chart for Kubernetes
type: application
version: v0.0.1 # x-release-please-version
dependencies:
  - name: grafana
    alias: grafana-source
    version: 6.60.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana-source.enabled
