grafana-source:
  fullnameOverride: grafana
  rbac:
    pspEnabled: false
  # adminUser: admin
  # adminPassword: strongpassword
  # Use an existing secret for the admin user.
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: grafana-initial-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  plugins:
  - grafana-piechart-panel

  # loki config
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000

  # prometheus config
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      uid: prometheus
      label: grafana_datasource
      labelValue: "1"

virtualService:
  name: grafana
  namespace: grafana
  gateway: istio-ingress/kube-gateway
  internalHost: grafana.kube.local
  port: 80
  serviceName: grafana
