kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: {{ .Values.name }}
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-issuer-url: https://dex.kube.local
      oidc-client-id: kubelogin
      oidc-ca-file: /etc/ca-certificates/dex/ca.pem
      oidc-username-claim: email
      oidc-groups-claim: groups
nodes:
- role: control-plane
  image: {{ .Values.k8s_version }}
  extraMounts:
  - hostPath:  {{ .Values.repo_host_path }}
    containerPath: {{ .Values.repo_node_path }}
    readOnly: true
  - hostPath: {{ .Values.repo_host_path }}/{{ .Values.repo_name }}/.ssl/ca.pem
    containerPath: /etc/ca-certificates/dex/ca.pem
    readOnly: true
