# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argocd-source:
  applicationSet:
    enabled: false

  configs:
    params:
      server.insecure: false

  dex:
    enabled: false

  notifications:
    enabled: false

  server:
    ingress:
      enabled: true
      https: true
      hosts:
      - argocd.local
      tls:
      - hosts:
        - argocd.local
        secretName: argocd.dex-tls
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
      # Required to support sycn-wave on ArgoCD Application kind
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
      # Required to fix the out-of-sync issues on the Istio apps suite
      resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
        jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
      resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
        jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
          - '.webhooks[]?.failurePolicy'
      # Required to fix the out-of-sync issues on the Knative apps suite
      resource.compareoptions: |
        # disables status field diffing in specified resource types
        ignoreAggregatedRoles: true
