apiVersion: v2
name: loki
description: Grafana Loki Helm chart for Kubernetes
type: application
version: v0.0.1 # x-release-please-version
dependencies:
  - name: loki
    alias: loki-source
    version: 5.36.3
    repository: https://grafana.github.io/helm-charts
    condition: loki-source.enabled
