loki-source:
  fullnameOverride: loki
  loki:
    auth_enabled: false
    storage:
      type: filesystem
    commonConfig:
      replication_factor: 1
    query_range:
      parallelise_shardable_queries: false
    limits_config:
      split_queries_by_interval: 0
    query_scheduler:
      max_outstanding_requests_per_tenant: 10000
  monitoring:
    dashboards:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
  test:
    enabled: false
  singleBinary:
    replicas: 1 # https://grafana.com/docs/loki/next/installation/helm/install-monolithic/
    # decrease log level from info to error to reduce log output
    extraArgs: [ "-log.level=error" ]
