apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-app
spec:
  template:
    metadata:
      annotations:
        # For testing purposes set request-per-second to 1 to force scaling
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/metric: "rps"
      labels:
        service: "ksample"
    spec:
      containers:
        - image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config
            mountPath: "/etc/nginx"
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: "nginx.conf"
            path: "nginx.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen       80;

        location / {
          return 200 'Hello world from initium-platform!';
        }
      }
    }
