otlp-collector-source:
  fullnameOverride: otlp
  mode: daemonset
  presets:
    kubernetesAttributes:
      enabled: true
    logsCollection:
      enabled: true
  config:
    receivers:
      otlp:
        protocols:
          http:

    processors:
      batch: {}

      attributes:
        actions:
        - action: insert
          key: log_iostream
          from_attribute: log.iostream
        - action: insert
          key: loki.attribute.labels
          value: log_iostream

      resource:
        attributes:
        - action: insert
          key: namespace_name
          from_attribute: k8s.namespace.name
        - action: insert
          key: pod_name
          from_attribute: k8s.pod.name
        - action: insert
          key: container_name
          from_attribute: k8s.container.name
        - action: insert
          key: container_restart_count
          from_attribute: k8s.container.restart_count
        - action: insert
          key: loki.resource.labels
          value: namespace_name, pod_name, container_name, container_restart_count

    exporters:
      loki:
        endpoint: http://loki.loki:3100/loki/api/v1/push
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [attributes, resource, batch]
          exporters: [loki]

# enable opentelemetry collector debug logging
#      telemetry:
#        logs:
#          level: "DEBUG"
#          development: true
#          encoding: "json"
