virtualService:
  enabled: false
  name: prometheus
  namespace: prometheus
  gateway: istio-ingress/kube-gateway
  port: 9090
  serviceName: kube-prometheus-stack-kube-prometheus

kube-prometheus-stack-source:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
    # rbac:
    #   pspEnabled: false
  grafana:
    # external grafana app is used by default
    enabled: false

    namespaceOverride: "grafana"
    # ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
    forceDeployDatasources: true
    # ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
    forceDeployDashboards: true

  prometheus:
    prometheusSpec:
      enableRemoteWriteReceiver: true
  # Required to fix the out-of-sync issues on the this apps suite
  kubelet:
    serviceMonitor:
      cAdvisorRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
      probesRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
      resourceRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
      relabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
