apiVersion: v2
name: istiod
description: istiod wrapper chart
type: application
version: v0.1.0 # x-release-please-version
dependencies:
  - name: istiod
    alias: istiod-source
    version: 1.17.1
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio-source.enabled
