apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-prometheus-app
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: sample-prometheus-app
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-prometheus-app
        release: kube-prometheus-stack
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "5m"
    spec:
      containers:
        # TO DO this is just a sample image and it should be replaced
        - image: "quay.io/brancz/prometheus-example-app:v0.3.0"
          ports:
            - containerPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: sample-prometheus-app
    release: kube-prometheus-stack
  name: sample-prometheus-app
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-prometheus-app
      release: kube-prometheus-stack
  podMetricsEndpoints:
    - port: user-port
