name: Upload assets

on:
  release:
    types:
      - published

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload files to a GitHub release
        run: |
          source .envrc
          cat manifests/app-of-apps.yaml | envsubst > app-of-apps.yaml
          ./scripts/upload-assets.sh ${{ github.repository }} app-of-apps.yaml ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          KKA_REPO_URI: https://github.com/${{ github.repository }}.git
          KKA_REPO_BRANCH: ${{ github.ref_name }}
