name: Upload assets

on:
  release:
    types:
      - published

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3

      - uses: actions/checkout@v4

      - name: Upload files to a GitHub release
        run: |
          helm template manifests/bootstrap --set revision=${{ github.ref_name }} > app-of-apps.yaml
          ./scripts/upload-assets.sh ${{ github.repository }} app-of-apps.yaml ${{ github.ref }}
          yq '.argocd-source' ./addons/argocd/values.yaml > argocd-helm-values.yaml
          ./scripts/upload-assets.sh ${{ github.repository }} argocd-helm-values.yaml ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
