name: Run Integration Tests

on:
  pull_request_review:
    types:
      - submitted

jobs:
  integration-tests:
    if: github.event.review.state == 'approved'
    strategy:
      matrix:
        KKA_K8S_VERSION:
          [
            "kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315",
            "kindest/node:v1.25.3@sha256:f1de3b0670462f43280114eccceab8bf1b9576d2afe0582f8f74529da6fd0365",
          ]
    runs-on:
      labels: ubuntu-latest-4-cores
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Integration test
        if: "!startsWith(github.event.pull_request.title, 'docs:')"
        id: tests
        run: |
          # Install asdf and expose to PATH
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
          . $HOME/.asdf/asdf.sh
          # Add asdf plugins and install tools in .tool-versions
          make asdf_install
          # Create a local branch to allow the next step to work
          git checkout -b ci
          # Deploy cluster
          make ci
          # Run tests
          make integration-test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KKA_AOA_EXCLUDE_DEX: true
          KKA_AOA_EXCLUDE_PROMETHEUSSTACK: true
          KKA_AOA_EXCLUDE_OPENTELEMETRY: true
          KKA_K8S_VERSION: ${{ matrix.KKA_K8S_VERSION }}

# https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
# This action should succeed if the tests are skipped or have passed
      - name: Status Check
        run: |
          if [[ ${{ steps.tests.outputs.outcome }} == 'skipped' || ${{ steps.tests.outputs.outcome }} == 'success' ]]; then exit 0; else exit 1; fi
