name: Run Unit Tests

on:
  pull_request_review:
    types:
      - submitted

jobs:
  create-cluster:
    if: github.event.review.state == 'approved' && !startsWith(github.event.pull_request.title, 'docs:')
    strategy:
      matrix:
        KKA_K8S_VERSION:
          [
            "kindest/node:v1.23.13@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315",
            "kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315",
            "kindest/node:v1.25.3@sha256:f1de3b0670462f43280114eccceab8bf1b9576d2afe0582f8f74529da6fd0365",
          ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Unit test
        run: |
          # Install envsubst
          sudo apt-get update && sudo apt-get install -y gettext
          # Install asdf and expose to PATH
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
          . $HOME/.asdf/asdf.sh
          # Add asdf plugins and install tools in .tool-versions
          make asdf_install
          # Create a local branch to allow the next step to work
          git checkout -b ci
          # Deploy cluster
          make ci
          # Run tests
          make unit-test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KKA_DEPLOY_MINIMAL: true
          KKA_K8S_VERSION: ${{ matrix.KKA_K8S_VERSION }}
