
name: nodejs

on: [push]

jobs:
  build:
    container:
      image: ghcr.io/nearform/k8s-kurated-addons-cli
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Check for dockerenv file
        run: ls